# Generated by Django 2.0.8 on 2018-08-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20180825_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
